language: csharp
mono: none
dotnet: 3.0
services:
    - docker
script:
- dotnet build Gotham/Gotham.web/
- dotnet build Gotham/Gotham.web.acceptanceTests/
- dotnet test Gotham/Gotham.web.acceptanceTests/
- docker build -t testgotham -f ./Gotham/Dockerfile .